### ISSUE TITLE
Get "Industry" font

### ISSUE THREAD

**Issue by pdhoopr** [BitBrew/brand-identity-and-style-guide#4]
The "Industry" font family doesn't appear to be loading/used on the style guide. I believe Bobby said this is because we don't actually own the font yet...so we should probably get it at some point! Then we can add it to the page.

**Comment by mehdimas** [comment]
Looks like it is available on Typekit: https://typekit.com/fonts/industry

**Comment by pdhoopr** [comment]
Closed by #6.
